[package]
name = "odp_app"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
polars = { version = "0.41.3", features = ["lazy"] }
reqwest = "0.12.5"
serde = "1.0.204"
serde_json = "1.0.120"
tokio = "1.38.1"
